name: Check doc
on:
  push:
    paths:
      - documentation/**

jobs:
  check-doc:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./documentation
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install .
        name: Install documentation tools
      - run: npm run linter
        name: Linter
      - run: npm run builder
        name: Builder

  trigger-doc-build:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: check-doc
    steps:
      - name: Trigger documentation build
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          event-type: Trigger documentation build workflow
